# Generated by Django 2.2.4 on 2021-06-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registeration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='request',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='login_registeration_app.Request'),
            preserve_default=False,
        ),
    ]
