# Generated by Django 2.2.4 on 2021-06-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registeration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='login_registeration_app.User')),
            ],
        ),
    ]
