# Generated by Django 2.2.4 on 2021-06-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registeration_app', '0002_lol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfollowings', to='login_registeration_app.User')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfollowers', to='login_registeration_app.User')),
            ],
        ),
    ]
