# Generated by Django 2.2.4 on 2021-06-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registeration_app', '0002_auto_20210605_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='request',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='login_registeration_app.Request'),
        ),
    ]
