# Generated by Django 2.2.4 on 2021-06-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registeration_app', '0003_auto_20210605_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='request',
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='login_registeration_app.User'),
            preserve_default=False,
        ),
    ]
