# Generated by Django 2.2.4 on 2021-06-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music',
        ),
    ]
