# Generated by Django 2.2.4 on 2021-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_music_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
